services:
  db:
    image: mysql:latest
    container_name: rpg_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: rpg_db        # Nombre de la base de datos
      MYSQL_ROOT_PASSWORD: root     # Contraseña del superusuario
      MYSQL_USER: usuario_rpg       # Usuario para la aplicación
      MYSQL_PASSWORD: proyecto_rpg  # Contraseña del usuario
    ports:
      - "3306:3306"                 # MySQL usa el puerto 3306 por defecto 
    volumes:
      # Mapea tu archivo local a la carpeta especial de Docker
      - ./app/bd/init.sql:/docker-entrypoint-initdb.d/init.sql
      
      # 2. Volumen de persistencia (Memory Card) [cite: 1137, 1138]
      # Para que no pierdas tus personajes al borrar el contenedor
      - mysql_data:/var/lib/mysql


  app:
    build: .  # Esto le dice que use el Dockerfile de esta carpeta
    container_name: rpg_game
    depends_on:
      - db    # Espera a que la base de datos esté lista
    environment:
      - DB_HOST=db  # IMPORTANTE: Dentro de Docker, el host no es 'localhost', es el nombre del servicio 'db'
    volumes:
      - ./app:/app # Sincroniza tu código para que los cambios se vean al instante
    stdin_open: true # Permite interactuar con la consola (input)
    tty: true        # Permite interactuar con la consola (input)

volumes:
  mysql_data: